// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBSAygcIAvSyfetWnNBx66SRpD3JnZeU',
    appId: '1:888536597068:web:ff77edb7ddc31686f8aae9',
    messagingSenderId: '888536597068',
    projectId: 'inventory-app-8189b',
    authDomain: 'inventory-app-8189b.firebaseapp.com',
    storageBucket: 'inventory-app-8189b.firebasestorage.app',
    measurementId: 'G-9Y70PYKHGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6X9YiAQoR1htrkhwvdV2xCxZ8f819zcc',
    appId: '1:888536597068:android:153a1a79539c3853f8aae9',
    messagingSenderId: '888536597068',
    projectId: 'inventory-app-8189b',
    storageBucket: 'inventory-app-8189b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2ecNJd5yqvY6Vnkmt7Wg_tR_7u5k3V0',
    appId: '1:888536597068:ios:c1736d6798273382f8aae9',
    messagingSenderId: '888536597068',
    projectId: 'inventory-app-8189b',
    storageBucket: 'inventory-app-8189b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2ecNJd5yqvY6Vnkmt7Wg_tR_7u5k3V0',
    appId: '1:888536597068:ios:c1736d6798273382f8aae9',
    messagingSenderId: '888536597068',
    projectId: 'inventory-app-8189b',
    storageBucket: 'inventory-app-8189b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBSAygcIAvSyfetWnNBx66SRpD3JnZeU',
    appId: '1:888536597068:web:d63bc5b40f2cb443f8aae9',
    messagingSenderId: '888536597068',
    projectId: 'inventory-app-8189b',
    authDomain: 'inventory-app-8189b.firebaseapp.com',
    storageBucket: 'inventory-app-8189b.firebasestorage.app',
    measurementId: 'G-DKVB8EBLXE',
  );
}
